apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-pod
        image: zoomcamp-model:3.11.5-hw10
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "580m"
        ports:
        - containerPort: 9696
